# Generated by Django 6.1 on 2026-08-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('Salary', 'Salary'), ('Pocket Money', 'Pocket Money'), ('Scholarship', 'Scholarship'), ('Freelance', 'Freelance'), ('Business', 'Business'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
